# 参考 `application-example.yaml` 并在处添加订阅规则，请注意缩进
# Refer to `application-example.yaml` and add subscription rules there，please note the indentation

application:
  config:
    domain-detect:
      enable: true
      timeout: 10

    exclude:
      # 屏蔽此域会导致Edge浏览器翻译不可用
      - "edge.microsoft.com"
      # 屏蔽此域会导致小米天气网络异常
      - "metok.sys.miui.com"
      # 屏蔽此域会导致10086 App登陆异常
      - "client.app.coc.10086.cn"
      # 屏蔽此域会导致MSN页面无法正常加载
      - "assets.msn.com"

  rule:
    remote:
      - name: AdGuard 防跟踪保护过滤器
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_3_Spyware/filter.txt
        type: easylist

      - name: AdGuard URL跟踪过滤器
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_17_TrackParam/filter.txt
        type: easylist

      - name: AdGuard 恼人广告过滤器
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_14_Annoyances/filter.txt
        type: easylist

      - name: AdGuard 解除搜索广告和自我推销过滤器
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_10_Useful/filter.txt
        type: easylist

      - name: xndeye web-ad-rule
        path: https://raw.githubusercontent.com/xndeye/web-ad-rule/master/easylist.txt
        type: easylist

      - name: 217heidai rule
        path: https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockdns.txt

      - name: d3Host List by d3ward
        path: https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.txt
        type: hosts
      
      - name: 大圣净化
        path: https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts
        type: hosts
      
      - name: crazy-max/WindowsSpyBlocker
        path: https://cdn.jsdelivr.net/gh/crazy-max/WindowsSpyBlocker@master/data/hosts/spy.txt
        type: hosts
        
      - name: 8680/GOODBYEADS 补充规则
        path: https://raw.githubusercontent.com/8680/GOODBYEADS/refs/heads/master/data/mod/adblock.txt



    local:
      - name: 'xndeye private adblock list'
        path: 'rule/private.txt'
        type: easylist

  output:
    file_header: |
      Title: Seameee adblock list of ${type}
      Last Modified: ${date}
      Homepage: https://github.com/Seameee/adblock_list

    files:
      - name: easylist.txt
        type: easylist
        filter:
          - basic
          - wildcard
          - unknown

      - name: dns.txt
        type: easylist
        file_header: |
          Title: Seameee adblock list of dns 
          Last Modified: ${date}
          Homepage: https://github.com/Seameee/adblock_list
        filter:
          - basic
          - wildcard

      - name: modify.txt
        type: easylist
        filter:
          - unknown

      - name: dnsmasq.conf
        type: dnsmasq

      - name: clash.yaml
        type: clash

      - name: smartdns.conf
        type: smartdns

      - name: hosts
        type: hosts
